openapi: 3.1.0

info:
  title: MAS Diagnostics API
  version: 1.0.0

paths:
  /vehicle/low-beam-light:
    get:
      x-us: US-0001
      operationId: getLowBeamLightState
      summary: Get low-beam light state

      responses:
        '200':
          description: Low-beam light state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LowBeamLightDTO'

components:
  schemas:
    LowBeamLightDTO:
      type: object
      required:
        - state
      properties:
        state:
          type: string
          enum:
            - ON
            - OFF